### ISSUE TITLE
[Issue] Class not found exception when exiting the GUI

### ISSUE THREAD

**Issue by Ligands** [NicJames2378/BQ-Forestry#14] opened 2020-01-10 00:11 UTC
**Description**
The game client crashes every time any bee retrieval task is closed.
Not sure if I'm doing something wrong, or it's just a problem with a recent version of something, as this seems like a pretty big issue to have not even been reported yet?

**Version Information**
 - Minecraft 1.12.2
 - Forge 14.23.5.2847
 - BQ Forestry 1.1.4
 - Better Questing 3.5.319
 - Forestry 5.8.2.409
(reproducable with no other mods installed)

**How To Reproduce**
1. Create a new bee retrieval task
2. Open the task
3. Click 'Done'
4. Client crashes

**Crash Log**
https://paste.dimdev.org/ecojamozah.mccrash

**Comment by NicJames2378** [comment] 2020-01-12 00:48
Thank you for bringing this to my attention. I would like to apologize for not updating in a long time, and for having an unstable version available on CurseForge. I am back to being able to maintain this mod now, though unforseen circumstances have causes a loss of everything not saved to this GitHub. As such, it may be a short time before I have a stable version released to go with the newest Better Questing version. However, I am working on it!

For the time being, you could try using Better Questing 3.5.312. FunwayGuy has changed a lot internally and I have not yet been able to update everything yet, but this particular version is verified to work (at least I am using it in-dev without an issue). **Remember to backup your quests file before attempting a downgrade!** If that doesn't work or you are unable to do that, I am trying my best to get it updated asap!

**Comment by Ligands** [comment] 2020-01-12 01:13
No worries, thanks for all your work, and FWIW your GUI really is fantastic! I wish the rest of Better Questing was as good as this :P

Honestly, even though it causes client crashes, this isn't actually a game-breaking issue (unless you're making a forestry-centric modpack, I guess), because Better Questing does still seem to update the Bee Retrieval Task correctly despite crashing, and I personally won't be modifying these quests very frequently.
(On top of that, the mod 'VanillaFix' makes client-side crashes very quick & easy to recover from, so it's really quite manageable)

**Comment by NicJames2378** [comment] 2020-01-31 07:22
Hey @Ligands , wanted to let you know I'll have a beta available in the next couple weeks with the new GUI and (hopefully) all the bugs fixed. If you're interested in receiving the latest updates on it, come join us over at my [Discord](https://discord.gg/vFhVKZ)!

**Comment by NicJames2378** [comment] 2020-02-25 00:20
The Beta took longer than expected as life typically does. I've got it uploading to CurseForge now, and should have this issue fixed! I am closing this issue for the time being, but feel free to open it back up if the issue is persisting. I have been unable to replicate using the newest updates of everything ( Forge 14.23.5.2847, BetterQuesting 3.5.323, Forestry 5.8.2.414, and JEI 4.15.0.291)

**Closed by NicJames2378** 2020-02-25 00:20 UTC
Labels: In-Progress, bug
